name: 'Setup environment for demisto-sdk'
description: 'Setup environment for every demisto-sdk workflow job'
author: 'Demisto-SDK'

inputs:
  python-version:
    required: true
    type: string
    description: "The python version"
  node-version:
    required: false
    type: string
    default: "16"
    description: "The node version to install"
  repository:
    required: false
    type: string
    default: ""
    description: "Whether to checkout to any other repository "


runs:
  using: 'composite'
  steps:

    - name: Python ${{ matrix.python-version }} - Setup Environment
      uses: ./.github/actions/setup_poetry_python_environment
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install npm
      run: |
        npm install
        echo $(echo '{"node_version": "'$(node --version)'","npm_list":'$(npm list --json)'}') > node_versions_info.json
      shell: bash
