-   id: content-test-runner
    name: content-test-runner
    description: Run content test using docker
    entry: run-content-tests
    language: system
    files: ^Packs/[^/]+/Integrations/[^/]+/[^/]+\.yml$
    types: [yaml]