- id: run-unit-tests
  name: Run unit tests
  description: Run content test using docker
  entry: run-unit-tests
  language: python
  files: ^Packs/.*/(?:Integrations|Scripts)/.*.yml$
- id: validate
  name: validate
  description: validate content
  entry: run-hook validate
  pass_filenames: true
  language: python
- id: format
  name: format
  description: format content
  entry: run-hook format
  language: python
