
- id: run-unit-tests
  name: Run unit tests
  description: Run content test using docker
  entry: demisto-sdk run-unit-tests
  language: python
  files: &files
    .*Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: validate
  name: validate
  description: validate content
  entry: demisto-sdk validate
  pass_filenames: true
  language: python
  require_serial: true
  files: *files

- id: format
  name: format
  description: Format non-code files, to comply with XSOAR standards.
  entry: demisto-sdk format
  args: ["-ud", "-y", "--no-validate"]
  language: python
  require_serial: true
  files: *files

- id: secrets
  name: secrets
  description: Check for secrets in files.
  entry: demisto-sdk secrets
  args: ["--ignore-entropy"]
  pass_filenames: false
  language: python

- id: no-implicit-optional
  name: no implicit optional
  description: Making code implicit-optional type hints PEP 484 compliant.
  entry: no-implicit-optional
  language: python
  files: *files
