
- id: run-unit-tests
  name: Run unit tests
  description: Run content test using docker
  entry: demisto-sdk run-unit-tests
  language: python
  files: &files
    .*Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: validate
  name: validate
  description: validate content
  entry: demisto-sdk validate
  pass_filenames: true
  language: python
  files: *files

- id: format
  name: format
  description: Format non-code files, to comply with XSOAR standards.
  entry: demisto-sdk format
  language: python
  files: *files
