- id: run-unit-tests
  name: Run unit tests
  description: Run content test using docker
  entry: run-unit-tests
  language: python
  files: ^Packs/.*/(?:Integrations|Scripts)/.*.yml$
- id: validate
  name: validate
  description: validate content
  entry: demisto-sdk validate
  pass_filenames: true
  language: python
  files: ^Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: format
  name: format
  description: format content
  entry: demisto-sdk format
  language: python
  files: ^Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: update-docker-image
  name: update docker image
  description: update docker image
  entry: demisto-sdk format -ud
  language: python
  files: ^Packs/.*/(?:Integrations|Scripts)/.*.yml$
