- id: content-test-runner
  name: content-test-runner
  description: Run content test using docker
  entry: run-content-tests
  language: python
- id: validate
  name: validate
  description: validate content
  entry: validate-hook
  pass_filenames: true
  language: python
- id: format
  name: format
  description: format content
  entry: format-hook
  language: python
