- id: run-unit-tests
  name: Run unit tests
  description: Run content test using docker
  entry: demisto-sdk run-unit-tests
  language: python
  files: .*Packs/.*/(?:Integrations|Scripts)/.*.yml$
- id: validate
  name: validate
  description: validate content
  entry: demisto-sdk validate
  pass_filenames: true
  language: python
  files: .*Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: format
  name: format
  description: Format non-code files, to comply with XSOAR standards.
  entry: demisto-sdk format
  language: python
  files: .*Packs/.*/(?:Integrations|Scripts)/.*.yml$

- id: update-docker-image
  name: update docker image
  description: Update the Docker image used by an integration or script.
  entry: demisto-sdk format -ud --no-validate
  language: python
  files: .*Packs/.*/(?:Integrations|Scripts)/.*.yml$
