[pytest]
addopts = --ignore=demisto_sdk/commands/init/templates --ignore=demisto_sdk/commands/generate_unit_tests/tests/test_files/outputs --ignore=demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py --ignore=demisto_sdk/commands/test_content/xsiam_tools/test_data.py
testpaths = demisto_sdk
timeout = 120
timeout_method = thread
faulthandler_timeout = 150
filterwarnings =
    ignore:Unknown config option. asyncio_mode:_pytest.config.PytestConfigWarning
    ignore::DeprecationWarning:typer
    ignore::FutureWarning:google
    ignore::urllib3.exceptions.InsecureRequestWarning
    ignore::pytest.PytestCollectionWarning
    ignore::DeprecationWarning:neo4j
