name: 'Run The Validate Command'
description: 'Run the validate -a command on content master'
author: 'Demisto-SDK'

inputs:
  artifacts-path-dir:
    required: true
    type: string
    description: "The path to the artifacts dir"

  artifact-name:
    required: false
    type: string
    description: "The name of of the artifact to upload"

  validate-arguments:
    required: false
    type: string
    description: "The validate command arguments to run."

  use-last-upload-commit:
    required: false
    type: boolean
    default: false
    description: "If true, use the last upload commit from the bucket instead of origin/master for --prev-ver"


runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup_test_environment
        with:
          python-version: '3.10'

      - name: Checkout content
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: demisto/content
          path: content

      - name: Get last upload commit
        id: get-last-upload-commit
        if: ${{ inputs.use-last-upload-commit == 'true' }}
        run: |
          source $(poetry env info --path)/bin/activate
          LAST_UPLOAD_COMMIT=$(python -c "from demisto_sdk.commands.common.tools import get_latest_upload_flow_commit_hash; print(get_latest_upload_flow_commit_hash())")
          echo "last_upload_commit=$LAST_UPLOAD_COMMIT" >> $GITHUB_OUTPUT
          echo "Last upload commit: $LAST_UPLOAD_COMMIT"
        shell: bash

      - name: Run Validate All
        run: |
          source $(poetry env info --path)/bin/activate
          cp demisto_sdk/commands/validate/sdk_validation_config.toml content/
          cd content
          git status
          mkdir -p ${{ inputs.artifacts-path-dir }}

          VALIDATE_ARGS="${{ inputs.validate-arguments }}"

          # If use-last-upload-commit is true, replace origin/master with the last upload commit
          if [ "${{ inputs.use-last-upload-commit }}" == "true" ] && [ -n "${{ steps.get-last-upload-commit.outputs.last_upload_commit }}" ]; then
            VALIDATE_ARGS=$(echo "$VALIDATE_ARGS" | sed "s|origin/master|${{ steps.get-last-upload-commit.outputs.last_upload_commit }}|g")
            echo "Using last upload commit for validation: ${{ steps.get-last-upload-commit.outputs.last_upload_commit }}"
          fi

          demisto-sdk validate $VALIDATE_ARGS
        shell: bash

      - name: Upload artifacts
        if: always()
        uses: ./.github/actions/upload_artifacts
        with:
          artifacts-path-dir: content/${{ inputs.artifacts-path-dir }}
          artifact-name: ${{ inputs.artifact-name }}
