# generated by datamodel-codegen:
#   filename:  connector.schema.json
#   timestamp: 2026-07-14T08:40:08+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import AnyUrl, BaseModel, Extra, Field, constr


class Category(BaseModel):
    __root__: constr(min_length=1)


class Ownership(BaseModel):
    class Config:
        extra = Extra.forbid

    team: Optional[str] = None
    maintainers: Optional[List[str]] = None


class Metadata(BaseModel):
    """
    Connector metadata.
    """

    class Config:
        extra = Extra.forbid

    title: constr(min_length=1) = Field(..., description='Display name.')
    description: constr(min_length=10) = Field(..., description='Brief description.')
    version: constr(regex=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ...,
        description="Semantic version (e.g., '1.0.0'). Validated as major.minor.patch.",
    )
    categories: List[Category] = Field(
        ..., description='Classification categories.', min_items=1
    )
    tags: Optional[List[str]] = Field(None, description='Searchable tags.')
    domain: Optional[str] = Field(None, description='Domain classification.')
    vendor: constr(min_length=1) = Field(
        ..., description='The vendor of the service being integrated.'
    )
    publisher: constr(min_length=1) = Field(
        ..., description='The publisher of this connector definition.'
    )
    author_image: Optional[
        Union[str, constr(regex=r'^[a-zA-Z0-9_.-]+\.(png|jpg|jpeg|svg)$')]
    ] = Field(
        None,
        description='Filename of the connector icon image in the connector root directory. Must match an actual image file. Allowed formats: png, jpg, jpeg, svg. Empty string means no icon.',
    )
    documentation: Optional[AnyUrl] = Field(
        None, description="URL to the connector's external documentation page."
    )
    ownership: Ownership
    is_recommended: Optional[bool] = Field(
        False,
        description='Whether the connector is recommended to users. When true, the connector is highlighted in the Data Sources Catalog list. Defaults to false.',
    )


class Settings(BaseModel):
    """
    Optional connector settings.
    """

    class Config:
        extra = Extra.forbid

    allow_skip_verification: Optional[bool] = Field(
        None, description='Allow skipping connection test.'
    )
    skip_cut_off_check: Optional[bool] = Field(
        None,
        description='When true, the platform skips the cut-off date check for this connector, making it available to all customers (new and existing) regardless of their onboarding date.',
    )
    required_features: Optional[List[constr(min_length=1)]] = Field(
        None,
        description='List of tenant features that must be active for this connector to be visible. All listed features must be active (AND logic). If empty or omitted, the connector is always visible.',
    )
    grouped: Optional[bool] = Field(
        False,
        description='When true, this connector is a Grouped Connector - both connection.yaml and configurations.yaml must declare their own top-level view_groups registry, every FieldGroup row in those files must declare a view_group, and every auth_options[] entry in every handler.yaml must declare a view_group. FieldGroup rows in connection.yaml resolve against connection.yaml view_groups; FieldGroup rows in configurations.yaml resolve against configurations.yaml view_groups; handler auth_options[].view_group resolve only against connection.yaml view_groups. When false or absent, no view_groups registry, FieldGroup view_group, or auth_option view_group may appear anywhere. Defaults to false.',
    )


class ConnectorYaml(BaseModel):
    """
    Schema for the connector.yaml file - defines connector identity and metadata.
    """

    class Config:
        extra = Extra.forbid

    enabled: Optional[bool] = Field(
        True,
        description='Whether the connector is enabled and available in the platform. Defaults to true. Set to false for example connectors.',
    )
    id: constr(min_length=3) = Field(
        ..., description='Unique identifier for the connector.'
    )
    metadata: Metadata = Field(..., description='Connector metadata.')
    settings: Optional[Settings] = Field(
        None, description='Optional connector settings.'
    )
