name: 'Setup testing environment for demisto-sdk jobs'
description: 'Setup testing environment for demisto-sdk jobs - that includes adding python/create-artifacts/install dependencies'
author: 'Demisto-SDK'

inputs:
  python-version:
    required: true
    type: string
    description: "The python version to setup"
  working-dir:
    required: false
    type: string
    default: ${{ github.workspace }}
    description: "On which working directory to run the setup-env, for example it can be done in content"
  poetry-install-arguments:
    required: false
    type: string
    default: "-E generate-unit-tests"
    description: "the arguments for the poetry install command"

runs:
  using: 'composite'
  steps:

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: '1.8.5' # TODO - Support Poetry v2.0.0

    - name: Check Poetry Consistency
      run: |
        cd ${{ inputs.working-dir }}
        poetry --version
        poetry check --lock
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
        cache-dependency-path: poetry.lock

    - name: Install dependencies with poetry
      run: |
        cd ${{ inputs.working-dir }}
        poetry install ${{ inputs.poetry-install-arguments }}
      shell: bash
