name: Conditional Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Files
        run: |
          mkdir additional_files
          echo "This is an additional file" > additional_files/file.txt

      - name: Conditionally Upload Artifact
        if: ${{ success() && steps.create-files.outputs.file-created == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: additional-files
          path: additional_files

      - name: Set Output
        id: create-files
        run: echo "::set-output name=file-created::true"