name: 'Setup testing environment for demisto-sdk jobs'
description: 'Setup testing environment for demisto-sdk jobs - that includes adding python/create-artifacts/install dependencies'
author: 'Demisto-SDK'

inputs:
  python-version:
    required: true
    type: string
    description: "The python version to setup"
  working-dir:
    required: false
    type: string
    default: ${{ github.workspace }}
    description: "On which working directory to run the setup-env, for example it can be done in content"
  poetry-export-arguments:
    required: false
    type: string
    default: "--extras generate-unit-tests"
    description: "the arguments for the poetry export command"

runs:
  using: 'composite'
  steps:
    - name: Setup uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}


    - uses: actions/cache/restore@v4
      name: Restore uv cache
      with:
        path: ~/.cache/uv
        key: python-${{ inputs.python-version }}-uv

    - name: Create venv with uv
      run: uv venv --python=${{ inputs.python-version }} 
      shell: bash

    - name: Install Poetry with uv
      run: uv pip install poetry
      shell: bash

    - name: Activate venv
      run: |
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
      shell: bash

    - name: Check pyproject.toml Consistency
      run: |
        cd ${{ inputs.working-dir }}
        poetry --version
        poetry check --lock
      shell: bash

    - name: Export Poetry dependencies
      run: poetry export -o requirements.txt --with dev ${{ inputs.poetry-export-arguments }}
      shell: bash

    - name: Install dependencies with uv
      run: uv pip install -r requirements.txt
      shell: bash

    - name: Install Demisto-SDK with uv
      run: uv pip install -e .
      shell: bash

    - uses: actions/cache/save@v4
      name: Save uv cache
      with:
        path: ~/.cache/uv
        key: python-${{ inputs.python-version }}-uv

