name: 'Upload artifacts to github summary'
description: 'Uploads artifacts to the github summary of a workflow'
author: 'Demisto-SDK'

inputs:
  artifacts-path-dir:
    required: true
    type: string
    description: "The path to the artifacts dir"

  artifact-name:
    required: false
    type: string
    default: $GITHUB_JOB
    description: "The name of of the artifact to upload"


runs:
  using: 'composite'
  steps:
    - name: Copy Files from home directory produced by SDK
      shell: bash
      run: |
        if [[ -d "$HOME/.demisto-sdk" ]]; then
          cp -r "$HOME/.demisto-sdk" ${{ inputs.artifacts-path-dir }}/demisto-sdk-home-folder-artifacts
          echo "Successfully copied $HOME/.demisto-sdk folder to ${{ inputs.artifacts-path-dir }}/demisto-sdk-home-folder-artifacts"
        else
          echo "The $HOME/.demisto-sdk folder does not exist, hence not uploading its artifacts"
        fi
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        include-hidden-files: true
        path: |
          ${{ inputs.artifacts-path-dir }}
