name: 'Test Summary'
description: 'Uploads artifacts, prints out a summary and check if there are any failed tests'
author: 'Demisto-SDK'

inputs:
  python-version:
    required: true
    type: string
    description: "The python version"
  artifacts-folder-name:
    required: false
    type: string
    description: "The folder name to save artifacts"
  group:
    required: false
    type: string
    description: "The folder name to save artifacts"
    default: "All-Tests"
  summary-display-options:
    required: false
    type: string
    description: "The test-summary display options"
    default: fs  # show all failed and skipped tests
  junit-path:
    required: true
    type: "string"
    description: "The junit-path file to post its summary in github workflow summary"
    default: ""



runs:
  using: 'composite'
  steps:
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifacts-folder-name }}-artifacts-python-${{ inputs.python-version }}-(${{ inputs.group }})
        path: |
          ${{ inputs.artifacts-folder-name }}
          node_versions_info.json
          .coverage
    - name: Print Summary of pytest results in workflow summary
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: ${{ inputs.junit-path}}
        summary: true
        display-options: ${{ inputs.summary-display-options }}
        fail-on-empty: false
    - name: Check if ${{ inputs.artifacts-folder-name }} have passed
      shell: bash
      if: always()
      run: |
        if [[ "$PYTEST_EXIT_CODE" -ne 0 ]]; then
          echo "There are ${{ inputs.artifacts-folder-name }} that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the ${{ inputs.artifacts-folder-name }} summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
        else
          echo "All ${{ inputs.artifacts-folder-name }} have passed, congratulations!"
        fi
        exit $PYTEST_EXIT_CODE
