"""Codegen sanity checks.

Every module in `strict_objects/_generated/` is auto-generated by
[`../regenerate.sh`](../regenerate.sh) from the UCC JSON Schemas in
[`../schemas/`](../schemas/). This test module verifies two invariants that
would silently break otherwise:

  1. Every generated module imports without raising (catches broken Pydantic
     v1 output, missing imports, invalid regex escaping, etc.).
  2. Every generated module exposes at least one `pydantic.BaseModel`
     subclass with a resolvable schema, so an accidental empty file cannot
     slip through unnoticed.

The tests use `importlib` + directory discovery so **adding a new schema
requires zero test-file changes**: as soon as `regenerate.sh` produces a new
Python file, it is automatically picked up here.
"""
import importlib
import pkgutil
from pathlib import Path
from typing import List

import pydantic
import pytest

_GENERATED_PACKAGE = "demisto_sdk.commands.content_graph.strict_objects._generated"


def _discover_generated_modules() -> List[str]:
    """Return the fully-qualified names of every non-dunder submodule under
    `_generated/`. Returns an empty list if the package has not been populated
    yet, in which case the parametrized tests below become no-ops."""
    try:
        package = importlib.import_module(_GENERATED_PACKAGE)
    except ImportError:
        return []
    if not hasattr(package, "__path__"):
        return []
    return [
        f"{_GENERATED_PACKAGE}.{modinfo.name}"
        for modinfo in pkgutil.iter_modules(package.__path__)
        if not modinfo.name.startswith("_")
    ]


_MODULES = _discover_generated_modules()


@pytest.mark.skipif(
    not _MODULES,
    reason=(
        "No generated modules present. Run "
        "`bash demisto_sdk/commands/content_graph/strict_objects/regenerate.sh` "
        "after the infra CI has copied the UCC schemas into strict_objects/schemas/."
    ),
)
@pytest.mark.parametrize("module_name", _MODULES)
def test_generated_module_imports_cleanly(module_name):
    """Every auto-generated module must import without side effects."""
    importlib.import_module(module_name)


@pytest.mark.skipif(
    not _MODULES,
    reason="No generated modules present (see test_generated_module_imports_cleanly).",
)
@pytest.mark.parametrize("module_name", _MODULES)
def test_generated_module_exposes_at_least_one_basemodel(module_name):
    """Every auto-generated module must expose at least one pydantic BaseModel
    subclass whose schema resolves. Catches accidentally empty schemas or
    codegen regressions that produce no models."""
    module = importlib.import_module(module_name)
    model_classes = [
        obj
        for obj in vars(module).values()
        if isinstance(obj, type)
        and issubclass(obj, pydantic.BaseModel)
        and obj is not pydantic.BaseModel
    ]
    assert model_classes, f"{module_name} defines no pydantic.BaseModel subclasses"

    # Resolving the schema forces Pydantic to evaluate every forward-ref and
    # constraint, so codegen bugs like an unresolved $ref surface here.
    for cls in model_classes:
        cls.schema()


def test_schemas_folder_exists_and_has_readme():
    """The infra-side CI job is expected to drop schema files into this folder.
    The README documents that contract and must always be present."""
    here = Path(__file__).resolve().parent.parent  # strict_objects/
    schemas_dir = here / "schemas"
    assert schemas_dir.is_dir(), f"missing folder: {schemas_dir}"
    assert (schemas_dir / "README.md").is_file(), (
        f"missing schemas/README.md at {schemas_dir}. This file documents the "
        f"contract the infra-side CI job must follow when copying UCC schemas."
    )
