ARG IMAGENAME

FROM --platform=amd64 ${IMAGENAME}

RUN python -m pip install --no-cache-dir pytest pytest-mock requests-mock pytest-asyncio pytest-xdist pytest-datadir-ng freezegun pytest-json pytest-cov