name: 'Setup python environment for demisto-sdk jobs'
description: 'Setup python environment for demisto-sdk jobs'
author: 'Demisto-SDK'

inputs:
  python-version:
    required: true
    type: string
    description: "The python version"
  node-version:
    required: false
    type: string
    default: "16"
    description: "The node version to install"


runs:
  using: 'composite'
  steps:

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8

    - name: Check Poetry Consistency
      run: |
        poetry --version
        poetry check --lock
      shell: bash

    - name: Install dependencies with poetry
      run: |
        poetry install -E generate-unit-tests
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        # cache: poetry
