name: Add PR link to Related Jira Issue
on:
  pull_request:
    types: [ closed ]

permissions:
  pull-requests: read

jobs:
  add_pr_link_to_related_jira_issue:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/demisto-sdk' && github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: '3.9'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec # v9
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Python Dependencies
        run: |
          poetry install
      - name: Run Linking pr to Jira Script
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_LINK: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
          USERNAME: ${{ secrets.GOLD_NG_LINK_PR_TO_JIRA_ISSUE_USER }}
          PASSWORD: ${{ secrets.GOLD_NG_LINK_PR_TO_JIRA_ISSUE_PASSWORD }}
          INSTANCE_URL: ${{ secrets.GOLD_NG_ENGINE_URL }}
        run: |
          echo "Checking for related Jira issues to PR: $PR_NUMBER"
          cd Utils/github_workflow_scripts/jira_integration_scripts
          poetry run python ./link_pr_to_jira_issue.py --url "$INSTANCE_URL" --pr_num "$PR_NUMBER" --pr_link "$PR_LINK" --pr_title "$PR_TITLE" --pr_body "$PR_BODY" --is_merged --username $USERNAME --password $PASSWORD
