name: Generate Validate Docs

on: pull_request

jobs:
  generate_validate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Check whether validate files changed
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Setup Environment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/setup_environment
        with:
          python-version: "3.10"

      - name: Generate Docs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: poetry run python demisto_sdk/commands/validate/generate_validate_docs.py validation_docs.md

      - name: Upload artifacts
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          path: validation_docs.md
          if-no-files-found: error

      - name: Output to GitHub Action Summary
        run: cat validation_docs.md >> $GITHUB_STEP_SUMMARY
