name: Run-Unit-Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  tests:
    name: Unit Tests / ${{ matrix.python-version }} (${{ matrix.group }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        group: [ 1, 2, 3, 4, 5 ]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: checkout-content-repo
#        run: |
#          git clone https://github.com/demisto/content.git
#          cd content
#          git config diff.renameLimit 5000
#          git --no-pager log -1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: |
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry check --lock
          poetry install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install npm
        run: npm install

      - name: Run pytest
        run: |
          source "$(poetry env info --path)/bin/activate"
          node demisto_sdk/commands/common/markdown_server/mdx-parse-server.js &
          node_pid=$!
          poetry run pytest --cov --splits 5 --group ${{ matrix.group }} -v
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python_version }}${{ matrix.group }}
          path: .coverage
