name: General

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  tests:
    name: Unit Tests / ${{ matrix.python-version }} (${{ matrix.group }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        group: [ 1, 2, 3, 4, 5 ]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: |
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry check --lock
          poetry install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install npm
        run: npm install

      - name: Run pytest
        continue-on-error: true
        run: |
          shopt -u globstar
          source "$(poetry env info --path)/bin/activate"

          TEST_FILES=$(find . -type f -name "*_test.py")
          # filter out files which are in .venv directory
          TEST_FILES=$(echo "$TEST_FILES" | sed -E 's/\S*\.venv\S*\.py//g')
          TEST_FILES=$(echo "$TEST_FILES" | sed -E 's/\S*demisto_sdk\/commands\/init\/templates\S*\.py//g')
          TEST_FILES=$(echo "$TEST_FILES" | sed -E 's/\S*demisto_sdk\/tests\/integration_tests\S*\.py//g')
          TEST_FILES=$(echo "$TEST_FILES" | sed -E 's/\S*demisto_sdk\/commands\/content_graph\/tests\S*\.py//g')

          echo $(echo '{"node_version": "'$(node --version)'","npm_list":'$(npm list --json)'}') > node_versions_info.json

          # Due to race conditions in the tests bringing up and down the node server, have the server available
          # For all the tests.
          node demisto_sdk/commands/common/markdown_server/mdx-parse-server.js &
          node_pid=$!

          echo "test-files are: $TEST_FILES"

          # poetry run pytest $TEST_FILES --store-durations
          mkdir test-results
          poetry run pytest $TEST_FILES -v --cov=demisto_sdk --cov-report=html --junitxml=test-results/junit.xml --splits 5 --group ${{ matrix.group }} || pytest_exit_code=$?
          echo "PYTEST_EXIT_CODE=$pytest_exit_code" >> $GITHUB_ENV

          kill $node_pid
          exit $pytest_exit_code
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python_version }}${{ matrix.group }}
          path: |
            .test_durations
            test-results/junit.xml
            node_versions_info.json
            coverage_html_report
      - name: Print Summary of pytest results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: test-results/junit.xml

          # Add a summary of the results at the top of the report
          # Default: true
          summary: true

          # Select which results should be included in the report.
          # Follows the same syntax as
          # `pytest -r`
          # Default: fEX
          display-options: fEX

          # Fail the workflow if no JUnit XML was found.
          # Default: true
          fail-on-empty: true
        run:
          if [[ "$PYTEST_EXIT_CODE" -ne 0 ]]; then
            echo "There are unit-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the tests summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "All unit-tests have passed"
          fi
          exit $PYTEST_EXIT_CODE
