name: Update .test-durations file

on:
  # schedule:
  #  - cron: "0 8 * * 0"  # Run every two weeks on Sunday at 8 AM UTC
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"


jobs:
  update-test-durations:
    name: Update .test-durations file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python 3.10 - Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          python-version: "3.10"

      - name: Run Unit Tests
        run: |
          source "$(poetry env info --path)/bin/activate"

          # Due to race conditions in the tests bringing up and down the node server, have the server available
          # For all the tests.
          node demisto_sdk/commands/common/markdown_server/mdx-parse-server.js &
          node_pid=$!

          mkdir unit-tests
          poetry run pytest . --ignore={demisto_sdk/commands/init/templates,demisto_sdk/tests/integration_tests,demisto_sdk/commands/content_graph,tests_end_to_end} --store-durations --junitxml=unit-tests/junit.xml || pytest_exit_code=$
          echo "PYTEST_EXIT_CODE=$pytest_exit_code" >> $GITHUB_ENV

          kill $node_pid
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-durations-artifacts-python-3.10
          path: |
            .test_durations
      - name: Update .test-durations
        run: |
          git status
          git add .test_durations
          git commit -m "Update .test-durations" || true
          git status
          # git push origin HEAD:refs/heads/update-test-durations
      - name: Create Draft PR
        run: |
          echo "bla"
          # gh pr create --base master --head update-test-durations --title "Update .test-durations" --body "This PR updates the .test-durations file." --draft --reviewer GuyAfik
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Python 3.10 - Test Summary Upload
        uses: ./.github/actions/test_summary
        with:
          python-version: "3.10"
          artifacts_folder_name: unit-tests
          junit-path: unit-tests/junit.xml
