name: Run content infrastracture tests
on: pull_request
env: 
  PYTHONPATH: $GITHUB_WORKSPACE/content

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name:  Get commit hash
        id: get-commit
        run: echo commit=$(git rev-parse HEAD) >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: demisto/content
          path: content
  

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Downloding the last demisto-sdk version
        run: |
          cd content 
          poetry install --with ci
          echo "starting uninstall of demisto-sdk .. "
          pip uninstall -y demisto-sdk
          echo "uninstall of demisto-sdk is done .. "
          echo "starting installing custom demisto-sdk of commit: ${{ steps.get-commit.outputs.commit }} "
          pip install git+https://github.com/demisto/demisto-sdk@${{ steps.get-commit.outputs.commit }}
          echo "added custom SDK"

      - name: tests
        run: |
          cd content
          poetry run pytest ./Tests/scripts/infrastructure_tests/ -v
          poetry run pytest ./Tests/Marketplace/Tests/ -v
          poetry run pytest ./Tests/tests -v
          poetry run pytest ./Tests/private_build/tests -v
          poetry run pytest Utils -v
          
