name: Run content infrastracture tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: ±±±±±±±±±  PWD1 ±±±±±±±±±±±±±±±
        run: pwd
      - name: Install Python Dependencies and downloding the last demisto-sdk version
        run: |
          git clone https://github.com/demisto/content -- ../..
          cd content
          poetry install --with ci
          echo "GITHUB_SHA : $GITHUB_SHA"
          poetry add git+https://github.com/demisto/demisto-sdk.git#${{github.sha}}
          echo "added custom SDK"
      - name: tests
        run:
          echo "what"
          pwd
          cd ../..
          pwd
          poetry run pytest ./Tests/scripts/infrastructure_tests/ -v
          poetry run pytest ./Tests/Marketplace/Tests/ -v
          poetry run pytest ./Tests/tests -v
          poetry run pytest ./Tests/private_build/tests -v
          poetry run pytest Utils -v
          
