name: Run content infrastracture tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Python Dependencies and downloding the last demisto-sdk version
        run: |
          cd ../.. 
          git clone https://github.com/demisto/content
          cd content
          poetry install --with ci
          echo "Last Commit: ${{ github.sha }}"
          poetry add git+https://github.com/demisto/demisto-sdk/pull/@${{ github.sha }}
          echo "added custom SDK"
      - name: pwd check
        run:
          pwd
          cd ../..
          echo pwd
          cd demisto-sdk
          echo pwd
      - name: tests
        run:
          cd ../..
          poetry run pytest ./Tests/scripts/infrastructure_tests/ -v
          poetry run pytest ./Tests/Marketplace/Tests/ -v
          poetry run pytest ./Tests/tests -v
          poetry run pytest ./Tests/private_build/tests -v
          poetry run pytest Utils -v
          
