name: Validate Content infra tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: ±±±±±±±±±  PWD1 ±±±±±±±±±±±±±±±
        run: pwd
      - name: Install Python Dependencies and downloding the last demisto-sdk version
        env: 
          GITHUB_SHA: ${{github.event.pull_request.merge_commit_sha}}
        run: |
          cd ../..
          git clone https://github.com/demisto/content 
          cd content
          poetry install --ci
          poetry remove demisto-sdk
          echo "removed default SDK"
          echo "GITHUB_SHA : $GITHUB_SHA"
          poetry add git+https://github.com/demisto/demisto-sdk.git#$GITHUB_SHA
          echo "added custom SDK"
          poetry run pytest ./Tests/scripts/infrastructure_tests/ -v
          poetry run pytest ./Tests/Marketplace/Tests/ -v
          poetry run pytest ./Tests/tests -v
          poetry run pytest ./Tests/private_build/tests -v
          poetry run pytest Utils -v
          
