name: Run content infrastracture tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Python Dependencies and downloding the last demisto-sdk version
        run: |
          cd ../.. 
          git clone https://github.com/demisto/content
          cd content
          poetry install --with ci
          cd ../../demisto-sdk
          export GIT_URL=$(git ls-remote --get-url origin | sed 's/\.git$//')
          echo GIT_URL
          echo "Last Commit: ${{ steps.last_commit.outputs.commit }}"
          poetry add git+https://github.com/demisto/demisto-sdk/pull/#${{ steps.last_commit.outputs.commit }}
          echo "added custom SDK"
      - name: tests
        run:
          cd ../..
          poetry run pytest ./Tests/scripts/infrastructure_tests/ -v
          poetry run pytest ./Tests/Marketplace/Tests/ -v
          poetry run pytest ./Tests/tests -v
          poetry run pytest ./Tests/private_build/tests -v
          poetry run pytest Utils -v
          
