name: Validate Content infra tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone content
        run: git clone https://github.com/demisto/content 
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: ±±±±±±±±±  PWD1 ±±±±±±±±±±±±±±±
        run: pwd
      - name: Install Python Dependencies
        run: |
          cd content
          poetry install
      - name: ±±±±±±±±±  PWD2 ±±±±±±±±±±±±±±±
        run: |
            pwd
      - name: Downloding the last demisto-sdk version
        env: 
          GITHUB_SHA: ${{github.event.pull_request.merge_commit_sha}}
        run: |
            echo "GITHUB_SHA : $GITHUB_SHA"
            poetry add poetry add git+https://github.com/demisto/demisto-sdk.git#$GITHUB_SHA
      - name: run unit tests
        run: |
           poetry run -m pytest ./Tests/scripts/infrastructure_tests/ ./Tests/Marketplace/Tests/ ./Tests/tests ./Tests/private_build/tests Utils -v

