name: Validate Content infra tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout-content
        with:
          repo: demisto/content  
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Python Dependencies
        run: poetry install
      - name: ±±±±±±±±±  PWD ±±±±±±±±±±±±±±±
        run: pwd
            cd ..
            cd ..
      - name: Downloding the last demisto-sdk version
        env:
          PULL: ${{ github.event.pull_request }}
          SHA_NUMBER: ${{github.event.SHA_NUMBER }}
        run: |
            echo "SHA_NUMBER $SHA_NUMBER"
            echo "PULL"
            echo "${{github.event.SHA_NUMBER}}"
            echo "${{github.event.pull_request.merge_commit_sha}}"
            poetry add git+https://github.com/demisto/demisto-sdk.git#$SHA_NUMBER
      - name: run unit tests
        run: |
           poetry run -m pytest ./Tests/scripts/infrastructure_tests/ ./Tests/Marketplace/Tests/ ./Tests/tests ./Tests/private_build/tests Utils -v

